"""
Report Generation Tools for MagenticOne

This module provides tools for generating and saving analysis reports
in Markdown format to the outputs directory.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Annotated, Optional


def save_markdown_report(
    content: Annotated[str, "The full Markdown content of the report to save"],
    filename: Annotated[Optional[str], "Optional filename (without extension). If not provided, auto-generates based on timestamp"] = None,
    title: Annotated[Optional[str], "Optional title for the report. If provided, will be added as H1 header if not already in content"] = None,
) -> str:
    """
    Save a Markdown report to the outputs directory.
    
    Creates a professional analysis report file with proper formatting,
    timestamp, and metadata. The report is saved to the outputs/ directory.
    
    Args:
        content: The full Markdown content of the report
        filename: Optional custom filename (without .md extension)
        title: Optional title to prepend to the report
        
    Returns:
        JSON string with status, file path, and metadata
    """
    try:
        # Ensure outputs directory exists
        output_dir = Path("outputs")
        output_dir.mkdir(exist_ok=True)
        
        # Generate filename if not provided
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        if filename:
            # Clean filename of any invalid characters
            clean_filename = "".join(c for c in filename if c.isalnum() or c in "._- ")
            clean_filename = clean_filename.replace(" ", "_")
            final_filename = f"{clean_filename}_{timestamp}.md"
        else:
            final_filename = f"crypto_report_{timestamp}.md"
        
        output_path = output_dir / final_filename
        
        # Build the report content
        report_parts = []
        
        # Add title if provided and not already in content
        if title and not content.strip().startswith("#"):
            report_parts.append(f"# {title}\n")
        
        # Add metadata header
        report_parts.append(f"\n---\n")
        report_parts.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        report_parts.append(f"**Report Type:** Crypto Analysis\n")
        report_parts.append(f"---\n\n")
        
        # Add main content
        report_parts.append(content)
        
        # Add footer
        report_parts.append(f"\n\n---\n")
        report_parts.append(f"*Report generated by MagenticOne Crypto Analysis Platform*\n")
        
        # Combine all parts
        final_content = "".join(report_parts)
        
        # Write the file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(final_content)
        
        result = {
            "status": "success",
            "message": f"Report saved successfully",
            "file_path": str(output_path.absolute()),
            "filename": final_filename,
            "size_bytes": len(final_content),
            "timestamp": timestamp,
        }
        
        return json.dumps(result, indent=2)
        
    except Exception as e:
        return json.dumps({
            "status": "error",
            "message": f"Failed to save report: {str(e)}",
        })


def create_analysis_report(
    symbol: Annotated[str, "The cryptocurrency symbol analyzed (e.g., 'BTC', 'ETH', 'SUI')"],
    summary: Annotated[str, "Executive summary of the analysis (2-3 sentences)"],
    price_analysis: Annotated[str, "Current price analysis and recent movements"],
    technical_analysis: Annotated[str, "Technical indicator analysis (RSI, MACD, etc.)"],
    signals: Annotated[str, "Trading signals and recommendations"],
    outlook: Annotated[str, "Market outlook and conclusion"],
    additional_sections: Annotated[Optional[str], "Optional additional Markdown sections to include"] = None,
) -> str:
    """
    Create a structured crypto analysis report and save it to outputs.
    
    Generates a professional, well-formatted Markdown report with
    standard sections for comprehensive crypto analysis.
    
    Args:
        symbol: Cryptocurrency symbol being analyzed
        summary: Executive summary
        price_analysis: Price movement analysis
        technical_analysis: Technical indicators analysis  
        signals: Trading signals and recommendations
        outlook: Market outlook and conclusion
        additional_sections: Optional extra Markdown content
        
    Returns:
        JSON string with status and file path
    """
    try:
        timestamp = datetime.now()
        
        # Build structured report
        report = f"""# {symbol.upper()} Analysis Report

## Executive Summary

{summary}

## Price Analysis

{price_analysis}

## Technical Analysis

{technical_analysis}

## Trading Signals

{signals}

## Market Outlook

{outlook}
"""
        
        # Add additional sections if provided
        if additional_sections:
            report += f"\n## Additional Analysis\n\n{additional_sections}\n"
        
        # Add disclaimer
        report += """
## Disclaimer

*This report is for informational purposes only and does not constitute financial advice. 
Cryptocurrency trading involves significant risk. Always conduct your own research before 
making investment decisions.*
"""
        
        # Save the report
        filename = f"{symbol.upper()}_analysis"
        return save_markdown_report(
            content=report,
            filename=filename,
            title=None,  # Title already in content
        )
        
    except Exception as e:
        return json.dumps({
            "status": "error", 
            "message": f"Failed to create report: {str(e)}",
        })


def create_comparison_report(
    symbols: Annotated[str, "Comma-separated list of symbols compared (e.g., 'BTC,ETH,SOL')"],
    comparison_summary: Annotated[str, "Summary of the comparison findings"],
    individual_analyses: Annotated[str, "Markdown-formatted analysis of each coin"],
    comparison_table: Annotated[str, "Markdown table comparing key metrics"],
    recommendations: Annotated[str, "Investment recommendations based on comparison"],
) -> str:
    """
    Create a multi-coin comparison report and save it to outputs.
    
    Generates a professional comparison report for analyzing
    multiple cryptocurrencies side by side.
    
    Args:
        symbols: Comma-separated symbols being compared
        comparison_summary: Overview of comparison findings
        individual_analyses: Analysis of each cryptocurrency
        comparison_table: Markdown table with metrics
        recommendations: Investment recommendations
        
    Returns:
        JSON string with status and file path
    """
    try:
        symbols_list = [s.strip().upper() for s in symbols.split(",")]
        symbols_display = " vs ".join(symbols_list)
        
        report = f"""# Cryptocurrency Comparison: {symbols_display}

## Comparison Summary

{comparison_summary}

## Metrics Comparison

{comparison_table}

## Individual Analysis

{individual_analyses}

## Recommendations

{recommendations}

## Disclaimer

*This report is for informational purposes only and does not constitute financial advice.
Cryptocurrency trading involves significant risk. Always conduct your own research before
making investment decisions.*
"""
        
        filename = f"comparison_{'_'.join(symbols_list)}"
        return save_markdown_report(
            content=report,
            filename=filename,
            title=None,
        )
        
    except Exception as e:
        return json.dumps({
            "status": "error",
            "message": f"Failed to create comparison report: {str(e)}",
        })


def create_custom_indicator_report(
    indicator_name: Annotated[str, "Name of the custom indicator"],
    description: Annotated[str, "Description of what the indicator measures"],
    formula: Annotated[str, "The formula or calculation method (can include code blocks)"],
    backtest_results: Annotated[str, "Results from backtesting the indicator"],
    usage_guide: Annotated[str, "How to interpret and use the indicator"],
    code_implementation: Annotated[Optional[str], "Optional Python code for the indicator"] = None,
) -> str:
    """
    Create a custom indicator documentation report.
    
    Generates a detailed report documenting a custom trading indicator
    including its formula, backtest results, and usage instructions.
    
    Args:
        indicator_name: Name of the indicator
        description: What the indicator measures
        formula: Calculation method/formula
        backtest_results: Backtesting results
        usage_guide: Interpretation guide
        code_implementation: Optional Python code
        
    Returns:
        JSON string with status and file path
    """
    try:
        report = f"""# Custom Indicator: {indicator_name}

## Overview

{description}

## Formula & Calculation

{formula}

## Backtest Results

{backtest_results}

## Usage Guide

{usage_guide}
"""
        
        if code_implementation:
            report += f"""
## Python Implementation

```python
{code_implementation}
```
"""
        
        report += """
## Notes

*Custom indicators should be thoroughly tested across different market conditions
before being used for trading decisions. Past performance does not guarantee future results.*
"""
        
        # Clean indicator name for filename
        clean_name = indicator_name.lower().replace(" ", "_")
        clean_name = "".join(c for c in clean_name if c.isalnum() or c == "_")
        
        filename = f"indicator_{clean_name}"
        return save_markdown_report(
            content=report,
            filename=filename,
            title=None,
        )
        
    except Exception as e:
        return json.dumps({
            "status": "error",
            "message": f"Failed to create indicator report: {str(e)}",
        })
